package frc.robot.util;

public enum Position {
  STOW,
  CUBE_INTAKE,
  CONE_INTAKE,
  CONE_STATION_INTAKE,
  COBRA_INTAKE,
  DOUBLE_SUBSTATION,
  CUBE_SCORE_MID,
  CUBE_SCORE_HIGH,
  CONE_SCORE_MID,
  CONE_SCORE_HIGH,
  HOLD,
  SINGLE_SUBSTATION
}
